import {normalizePlate,slotName,floorOf,price,initialState,book,checkout} from './logic.js';
const $=s=>document.querySelector(s),key='e-parking-demo-v1';let state,view='parking',floor=1,selected=null,found=null,paymentId=null,lastReceipt=null;
try{state=JSON.parse(localStorage.getItem(key));if(!state||state.version!==1||!Array.isArray(state.active)||!Array.isArray(state.history))state=initialState();}catch{state=initialState();}
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const date=n=>new Date(n).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'});
const duration=n=>{const m=Math.floor(Math.max(0,Date.now()-n)/60000);return `${Math.floor(m/60)} jam ${m%60} menit`;};
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4200);}
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{toast('Penyimpanan browser tidak tersedia. Demo tetap berjalan selama halaman terbuka.');}}
const car='<svg viewBox="0 0 28 36" aria-hidden="true"><rect x="5" y="2" width="18" height="32" rx="6" fill="currentColor" opacity=".25"/><path d="M8 10h12l-1-5H9zm0 15h12v5H8z" fill="currentColor"/><path d="M3 9v5m22-5v5M3 24v5m22-5v5" stroke="currentColor" stroke-width="2"/></svg>';
function map(){let rows='';for(let r=0;r<4;r++){const slots=Array.from({length:5},(_,i)=>(floor-1)*20+r*5+i+1);rows+=`<div class="row">${slots.map(n=>{const record=state.active.find(a=>a.slot===n);return `<button class="slot ${record?'occupied':''} ${selected===n?'selected':''} ${record?.id===state.mine?'mine':''} ${found?.slot===n?'found':''}" data-slot="${n}" ${record?'disabled':''} aria-label="Slot ${slotName(n)}, ${record?'terisi':'tersedia'}" aria-pressed="${selected===n}">${record?car:'<span aria-hidden="true">＋</span>'}<span>${slotName(n)}</span></button>`;}).join('')}</div>`;if(r<3)rows+='<div class="lane"><span>↑</span> JALUR KENDARAAN <span>↓</span></div>';}
return `<section class="panel"><div class="panel-top"><div><h2>Denah parkir</h2><div class="muted">${20-state.active.filter(a=>floorOf(a.slot)===floor).length} slot tersedia di lantai ini</div></div><div class="floors" aria-label="Pilih lantai">${[1,2,3].map(f=>`<button data-floor="${f}" class="${f===floor?'active':''}" aria-pressed="${f===floor}">Lantai ${f}</button>`).join('')}</div></div><div class="legend"><span><i></i>Tersedia</span><span><i class="busy"></i>Terisi</span><span><i class="chosen"></i>Dipilih / milik Anda</span></div><div class="lot">${rows}<div class="entry"><span>↗ MASUK</span><span>LANTAI ${floor} · 20 SLOT</span><span>KELUAR ↗</span></div></div></section>`;}
function detail(r){return `<div class="detail"><span>Nama</span><strong>${esc(r.name)}</strong></div><div class="detail"><span>Plat nomor</span><strong>${esc(r.plate)}</strong></div><div class="detail"><span>Lokasi</span><strong>Lantai ${floorOf(r.slot)} · ${slotName(r.slot)}</strong></div><div class="detail"><span>Mulai</span><strong>${date(r.start)}</strong></div><div class="detail"><span>Durasi</span><strong data-duration="${r.start}">${duration(r.start)}</strong></div><div class="detail"><span>Estimasi biaya</span><strong data-price="${r.start}">${money(price(r.start))}</strong></div>`;}
function bookingPanel(){const mine=state.active.find(r=>r.id===state.mine);if(mine)return `<section class="panel booking"><span class="tag">● PARKIR AKTIF</span><h2>Kendaraan Anda</h2><p class="selected-number">${slotName(mine.slot)}</p><div class="divider"></div>${detail(mine)}<button class="primary" data-checkout="${mine.id}">Selesaikan parkir →</button><p class="muted">Transaksi merupakan simulasi. Tidak ada uang yang ditagihkan.</p></section>`;return `<section class="panel booking"><span class="tag">RESERVASI PARKIR</span><h2>${selected?'Pilihan yang tepat.':'Siap untuk parkir?'}</h2><p class="selected-number">${selected?slotName(selected):'—'}</p><p class="muted">${selected?`Lantai ${floorOf(selected)} · slot tersedia`:'Pilih slot hijau pada denah untuk memulai.'}</p><div class="divider"></div><form id="book-form"><label class="field">Nama pengunjung<input id="name" maxlength="60" placeholder="Nama Anda" required autocomplete="name"></label><label class="field">Plat nomor<input id="plate" maxlength="14" placeholder="B 2026 XYZ" required autocapitalize="characters"></label><button class="primary" ${selected?'':'disabled'}>Mulai parkir →</button></form><p class="muted">Gunakan data contoh. Sesi ini hanya disimpan di browser Anda.</p></section>`;}
function render(){const labels={parking:['Tempat parkir','Temukan tempat Anda.','Pilih slot, parkir dengan tenang, dan lanjutkan hari Anda.'],find:['Temukan kendaraan','Mobil Anda, ditemukan.','Cari plat nomor untuk melihat lokasi dan sesi parkir.'],history:['Riwayat transaksi','Setiap perjalanan tercatat.','Lihat kembali simulasi transaksi parkir Anda.']};$('#breadcrumb').textContent=labels[view][0];$('#title').textContent=labels[view][1];$('#subtitle').textContent=labels[view][2];$('#available').textContent=60-state.active.length;$('#occupied').textContent=state.active.length;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const admin=$('#role').value==='admin';
if(view==='parking')$('#content').innerHTML=`${lastReceipt?`<div class="receipt">✓ Simulasi selesai · ${esc(lastReceipt.plate)} · ${money(lastReceipt.total)}. Slot ${slotName(lastReceipt.slot)} kembali tersedia.</div>`:''}<div class="workspace">${map()}${bookingPanel()}</div><div class="tip"><span>↗</span><div><b>Parkir dalam tiga langkah.</b><br>Pilih tempat → masukkan plat kendaraan → selesaikan parkir saat Anda kembali.</div></div>${admin?adminPanel():''}`;
if(view==='find')$('#content').innerHTML=`<section class="panel"><h2>Temukan kendaraan</h2><p class="muted">Coba plat contoh B 1234 ABC atau plat kendaraan yang Anda parkirkan.</p><form id="find-form" class="search-form"><label class="field">Plat nomor<input id="search" required maxlength="14" placeholder="Masukkan plat nomor" value="${esc(found?.plate||'')}"></label><button class="primary">Cari kendaraan →</button></form></section><div style="margin-top:22px" class="workspace">${map()}<section class="panel">${found?`<span class="demo-tag">KENDARAAN DITEMUKAN</span><p class="selected-number">${slotName(found.slot)}</p>${detail(found)}${admin||found.id===state.mine?`<button class="primary" data-checkout="${found.id}">Selesaikan parkir →</button>`:''}`:'<div class="empty">⌕<br>Lokasi kendaraan akan muncul di sini.</div>'}</section></div>`;
if(view==='history')$('#content').innerHTML=`<section class="panel"><div class="history-top"><div><h2>Riwayat transaksi</h2><p class="muted">${state.history.length} transaksi simulasi tersimpan</p></div><button class="secondary" id="export" ${state.history.length?'':'disabled'}>Unduh CSV ↓</button></div>${state.history.length?`<div class="table-wrap"><table><thead><tr><th>Kendaraan</th><th>Pengunjung</th><th>Slot</th><th>Waktu selesai</th><th>Total</th></tr></thead><tbody>${state.history.map(r=>`<tr><td>${esc(r.plate)}</td><td>${esc(r.name)}</td><td>${slotName(r.slot)}</td><td>${date(r.end)}</td><td>${money(r.total)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Belum ada transaksi.<br>Selesaikan satu sesi parkir untuk melihat riwayatnya.</div>'}</section>`;
bind();}
function adminPanel(){return `<section class="panel admin-list"><h2>Monitor kendaraan · Admin demo</h2><p class="muted">Peran simulasi untuk mencoba pencarian dan penyelesaian sesi semua kendaraan di browser ini.</p><div class="table-wrap"><table><thead><tr><th>Plat</th><th>Slot</th><th>Pengunjung</th><th>Aksi</th></tr></thead><tbody>${state.active.map(r=>`<tr><td>${esc(r.plate)}</td><td>L${floorOf(r.slot)} · ${slotName(r.slot)}</td><td>${esc(r.name)}</td><td><button class="secondary" data-checkout="${r.id}">Selesaikan</button></td></tr>`).join('')}</tbody></table></div></section>`;}
function bind(){document.querySelectorAll('[data-floor]').forEach(b=>b.onclick=()=>{floor=+b.dataset.floor;render();});document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{selected=+b.dataset.slot;render();});document.querySelectorAll('[data-checkout]').forEach(b=>b.onclick=()=>openBill(b.dataset.checkout));$('#book-form')?.addEventListener('submit',e=>{e.preventDefault();try{const r=book(state,{name:$('#name').value,plate:$('#plate').value,slot:selected});state.mine=r.id;lastReceipt=null;selected=null;save();render();toast(`Parkir dimulai di ${slotName(r.slot)}.`);}catch(err){toast(err.message);}});$('#find-form')?.addEventListener('submit',e=>{e.preventDefault();const plate=normalizePlate($('#search').value).replace(/\s/g,'');found=state.active.find(r=>r.plate.replace(/\s/g,'')===plate)||null;if(found)floor=floorOf(found.slot);render();if(!found)toast('Kendaraan tidak ditemukan atau sesi parkir sudah selesai.');});if($('#export'))$('#export').onclick=exportCsv;}
function openBill(id){const r=state.active.find(a=>a.id===id);if(!r)return;paymentId=id;$('#bill').innerHTML=`<div class="eyebrow">TRANSAKSI SIMULASI</div><h2 style="margin-top:12px">Selesaikan perjalanan.</h2>${detail(r)}<div class="bill-total">${money(price(r.start))}</div><p class="muted">Rp20.000 tarif awal + Rp5.000 untuk setiap jam penuh. Total dihitung kembali saat Anda menyelesaikan simulasi. Tidak ada pembayaran nyata.</p>`;$('#payment').showModal();}
$('#cancel-pay').onclick=()=>$('#payment').close();$('#confirm-pay').onclick=()=>{try{lastReceipt=checkout(state,paymentId);found=null;selected=null;save();$('#payment').close();view='parking';render();toast('Simulasi transaksi berhasil.');}catch(e){toast(e.message);}};
function exportCsv(){const cell=v=>'"'+String(v).replace(/^[=+\-@\t\r]/,"'$&").replace(/"/g,'""')+'"';const lines=[['Plat','Nama','Slot','Mulai','Selesai','Total IDR'],...state.history.map(r=>[r.plate,r.name,slotName(r.slot),new Date(r.start).toISOString(),new Date(r.end).toISOString(),r.total])];const url=URL.createObjectURL(new Blob(['\ufeff'+lines.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='e-parking-transaksi.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;selected=null;render();});$('#role').onchange=render;$('#reset').onclick=()=>{if(confirm('Reset semua sesi dan riwayat demo di browser ini?')){state=initialState();found=null;selected=null;lastReceipt=null;view='parking';save();render();toast('Demo direset.');}};
window.addEventListener('storage',e=>{if(e.key===key){try{const updated=JSON.parse(e.newValue);if(updated?.version===1){state=updated;found=null;render();}}catch{}}});setInterval(()=>{document.querySelectorAll('[data-duration]').forEach(el=>el.textContent=duration(+el.dataset.duration));document.querySelectorAll('[data-price]').forEach(el=>el.textContent=money(price(+el.dataset.price)));},1000);save();render();
